### PR TITLE
fix: class is initialized outside each event scope, and in case of two events in the same time-frame we get duplicated classes

### PR DESCRIPTION
**Pull request by GeoSot**
image

### CODE REVIEW

**Comment by benhall14** [comment]
Moving the $event_summary into the loop, will cause each event to override the previous, meaning that only one event will show, and it will show for every day until a new event overrides it. The class is setup this way by design, so that the mask-end can be applied. Overwriting the $class for each event means that you will only ever get the classes assigned to the last event.

**Comment by GeoSot** [comment]
image


At lines 1010 & 1012 the summary is initialized again.  So as a side effect, although the higher scope of the variable, inside each iteration, it is cleared and assigned again.

and at line 1033 (before the iteration finish, the summary variable is concatenated to `$calendar` string


However, if you insist, I am fine to just fix the $class variable, that messes my classes :smile:

**Comment by benhall14** [comment]
My apologies. You're correct :) 

I've been getting confused about the main month view. I'll merge this now.

**Comment by GeoSot** [comment]
Thank you a lot :)

**Pull request merged**
